title: My Portfolio
description: A showcase of my work and skills
baseurl: "/assign1"
url: "https://lhxen.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md

# Navigation
header_pages:
  - about.md
  - blog.md
  - projects.md
  - services.md
  - contact.md 